### ISSUE TITLE
Failed to spawn error with Atom 0.166.0.

### ISSUE THREAD

**Issue by bobrocke** [AtomLinter/linter-scss-lint#14]
Error in red dialog box in upper right corner:

Failed to spawn command scss-lint. Make sure scss-lint is installed and on your PATH

This just started with Atom 0.166.0. It didn't so it before.

**Comment by bobrocke** [comment]
I have the same error with Atom 0.168.0.

I ran `which scss-lint` and got back `/Users/bob/.rvm/gems/ruby-2.0.0-p247@rails3/bin/scss-lint`

So I added
```
'linter-scss-lint':
      'scssLintExecutablePath': '/Users/bob/.rvm/gems/ruby-2.0.0-p247@rails3/bin/scss-lint'
```
to my Atom config file.

I still get the same error about scss-lint not being installed.

**Comment by InSuperposition** [comment]
:+1: 
I get a similar error, I am also using RVM.

**Comment by karl-wednesday** [comment]
I started experiencing the same issue since sometime in early January.  Everything seemed to be working fine prior to that.

As far as I'm aware, the only thing that has changed is that I have updated Atom and all of its installed packages using Atom's built in updater, so perhaps the issue was introduced due to the Atom 0.166.0 update as @bobrocke suggests.

Unlike the other reporters, I am using rbenv via Homebrew.

`which scss-lint` reports that my path is `/Users/karl/.rbenv/shims/scss-lint`

**Comment by bobrocke** [comment]
Any progress with this? It's a problem and I don't know of another Atom SCSS linter.

**Comment by jclusso** [comment]
yea, still waiting on an update for this.

**Comment by nickroberts** [comment]
I get the same thing on 0.177.0.

**Comment by nickroberts** [comment]
I started Atom via the command line, and it worked. Odd.

This still should be addressed, me thinks.

Using rvm, as well.

**Comment by bobrocke** [comment]
Has this plug-in been abandoned?

**Comment by bobrocke** [comment]
I wonder if anyone using `rbenv` is having this problem?

**Comment by bobrocke** [comment]
Yes, I see that @karl-wednesday is using it. Dang.

**Comment by InSuperposition** [comment]
@nickroberts I get the same results. This issue may directly be related to AtomLinter or Atom Itself. https://github.com/AtomLinter/Linter/issues/150

**Comment by maban** [comment]
I'm getting this too. Opening Atom from the command line instead of the dock worked, but it's not an ideal solution.

**Comment by simmerz** [comment]
Getting this too with rbenv. It looks like it's because Atom is started without the user profile, so the version of ruby it sees isn't the same version that the terminal sees. Hence why starting from the terminal works.

**Comment by bobrocke** [comment]
@simmerz That's an interesting observation! How can I tell what version Atom finds when started from the terminal? Maybe I can configure scss-lint there?

**Comment by bobrocke** [comment]
Here's an issue with a resolution that worked for me: https://github.com/AtomLinter/linter-scss-lint/issues/39

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58

**Comment by idmarjr** [comment]
Hello guys!
I follow the instructions from `readme.md` to install sass-lint and looks like this issue is happening again :( (At least for me).

MacOSX 10.11
Atom 1.0.19
 
![screen shot 2015-10-13 at 15 42 58](https://cloud.githubusercontent.com/assets/301545/10464786/de3bb610-71c1-11e5-9763-c04e4e4b0873.png)

Any ideas of how can I fix it?

**Comment by Arcanemagus** [comment]
@idmarjr OS X "helps" you by striping the environment from any application launched from the GUI. You can either launch Atom from a terminal window, or specify the path the `scss-lint` in the settings.

**Comment by idmarjr** [comment]
@Arcanemagus I tried launch it from terminal.app but even this way it still happening. :/

**Comment by steelbrain** [comment]
@idmarj try specifying a full path to it in settings.

**Comment by idmarjr** [comment]
@steelbrain Awesome! It works.
I ran `which sass-lint` in terminal and than copy the returned path.
Go to `Atom > Preferences > Packages > linter-css-lint > Settings` and past that path in `Executable Path` field.

Appreciate your help guys!

**Comment by RhianWright** [comment]
Suddenly getting this error after upgrading to Atom V1.3.1

**Comment by Arcanemagus** [comment]
@RhianWright have you tried specifying the full path as outlined a few times in this thread?

**Comment by graysonhicks** [comment]
Go to Atom > Preferences > Packages > linter-css-lint > Settings and paste that path in Executable Path field.

@steelbrain @idmarjr This works, thanks!

**Comment by fahimfarookme** [comment]
Apparently the atom-scss-lint does not install the scss-lint gem. Try installing the gem manually. 
`gem install scss_lint`

**Comment by Arcanemagus** [comment]
@fahimfarookme That's part of the readme's installation steps: https://github.com/AtomLinter/linter-scss-lint#scss-lint-installation :wink:.

**Comment by webzorg** [comment]
RVM case. http://stackoverflow.com/questions/26247926/how-to-solve-usr-bin-env-ruby-executable-hooks-no-such-file-or-directory 
which scss-lint, put the path in plugin default executable and change bin with wrappers.
